/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class AppAssets {
  static const String backgroundImage = "assets/images/background_image.png";
  static const String festival1 = "assets/images/festival_1.png";
  static const String festival2 = "assets/images/festival_2.png";
  static const String festival3 = "assets/images/festival_3.png";
  static const String festival4 = "assets/images/festival_4.png";
  static const String icSplashLogo = "assets/images/ic_splash_logo.png";
  static const String ofImage1 = "assets/images/of_image_1.png";
  static const String ofImage2 = "assets/images/of_image_2.png";
  static const String ofImage3 = "assets/images/of_image_3.png";
  static const String ofImage4 = "assets/images/of_image_4.png";
  static const String ofImage5 = "assets/images/of_image_5.png";
  static const String ofImage6 = "assets/images/of_image_6.png";
  static const String ofImage7 = "assets/images/of_image_7.png";
  static const String ofImage8 = "assets/images/of_image_8.png";
  static const String pracharTitle = "assets/images/prachar_title.png";
  static const String robotoBlack = "assets/fonts/Roboto-Black.ttf";
  static const String robotoBlackitalic = "assets/fonts/Roboto-BlackItalic.ttf";
  static const String robotoBold = "assets/fonts/Roboto-Bold.ttf";
  static const String robotoBoldcondensed = "assets/fonts/Roboto-BoldCondensed.ttf";
  static const String robotoBoldcondenseditalic = "assets/fonts/Roboto-BoldCondensedItalic.ttf";
  static const String robotoBolditalic = "assets/fonts/Roboto-BoldItalic.ttf";
  static const String robotoCondensed = "assets/fonts/Roboto-Condensed.ttf";
  static const String robotoCondenseditalic = "assets/fonts/Roboto-CondensedItalic.ttf";
  static const String robotoItalic = "assets/fonts/Roboto-Italic.ttf";
  static const String robotoLight = "assets/fonts/Roboto-Light.ttf";
  static const String robotoLightitalic = "assets/fonts/Roboto-LightItalic.ttf";
  static const String robotoMedium = "assets/fonts/Roboto-Medium.ttf";
  static const String robotoMediumitalic = "assets/fonts/Roboto-MediumItalic.ttf";
  static const String robotoRegular = "assets/fonts/Roboto-Regular.ttf";
  static const String robotoThin = "assets/fonts/Roboto-Thin.ttf";
  static const String robotoThinitalic = "assets/fonts/Roboto-ThinItalic.ttf";
  static const String selectedCheck = "assets/images/selected_check.jpg";
  static const String webLogo = "assets/images/web_logo.png";
}
